# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/firebolt
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host-address: localhost
  protocol: http